### ISSUE TITLE
Line breaks in paragraphs are rendered with no space

### ISSUE THREAD

**Issue by FlippingBinary** [DioxusLabs/docsite#221] opened 2024-03-17 15:09 UTC
The website is rendering inter-paragraph line breaks from the `.md` files without any space between them.

For example, the URL `https://dioxuslabs.com/learn/0.5/router/example` does not render the spaces in `you're building` and `small website`, which is where the line breaks occur in the `.md` file:

https://github.com/DioxusLabs/docsite/blob/2e9fc80c0112e552d5b86447667af123adbf8d51/docs-src/0.5/en/router/example/index.md?plain=1#L3-L5

Here is what it looks like in my browser (Vivaldi/Chromium-based):

![image](https://github.com/DioxusLabs/docsite/assets/35066367/ecfa2c59-9245-4932-95e4-7212cb01ff3b)

You can see in the inspect view that the paragraph appears in three quoted regions as if they are three separate elements, which might explain why they are rendered without spaces between them.

GitHub's interface renders the same `.md` properly:

![image](https://github.com/DioxusLabs/docsite/assets/35066367/4156c536-0903-4de0-ba0f-362db014aab5)

You can see in the inspect view that the paragraph is combined into one element.

**Comment by ealmloff** [comment] 2024-03-17 16:34
Closing this as a duplicate of https://github.com/DioxusLabs/include_mdbook/issues/3

**Closed by ealmloff** 2024-03-17 16:34 UTC
